// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDu1RcFKKE3By2xS1B_9I1GNcPgKcIGio',
    appId: '1:77725287147:web:0a0ea24a02e734d10634ae',
    messagingSenderId: '77725287147',
    projectId: 'gizigenuis',
    authDomain: 'gizigenuis.firebaseapp.com',
    storageBucket: 'gizigenuis.appspot.com',
    measurementId: 'G-GKVXM3CSDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM8tgNZMVJJHLBtlBd8OGqcoObkI3gni8',
    appId: '1:77725287147:android:6ec1270ec5638d310634ae',
    messagingSenderId: '77725287147',
    projectId: 'gizigenuis',
    storageBucket: 'gizigenuis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALgWW5LVJWGegGRxOL6b__BBajnd1HBwM',
    appId: '1:77725287147:ios:bf9da986a4eab8a10634ae',
    messagingSenderId: '77725287147',
    projectId: 'gizigenuis',
    storageBucket: 'gizigenuis.appspot.com',
    iosClientId: '77725287147-uiiak9isdihm78k43msbdo2jh505o6si.apps.googleusercontent.com',
    iosBundleId: 'com.example.giziGenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALgWW5LVJWGegGRxOL6b__BBajnd1HBwM',
    appId: '1:77725287147:ios:6210ca15b3de9ebd0634ae',
    messagingSenderId: '77725287147',
    projectId: 'gizigenuis',
    storageBucket: 'gizigenuis.appspot.com',
    iosClientId: '77725287147-7a8gkoo2avbodaundljqvki8gc85l869.apps.googleusercontent.com',
    iosBundleId: 'com.example.giziGenius.RunnerTests',
  );
}
